"""add completed_at to lesson_progress

Revision ID: 4756cc2e896c
Revises: af2a32a2ac76
Create Date: 2026-07-31 23:28:15.971570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4756cc2e896c'
down_revision: Union[str, Sequence[str], None] = 'af2a32a2ac76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_progress', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_progress', 'completed_at')
    # ### end Alembic commands ###
